FROM debian
MAINTAINER tmlkshk
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y default-jdk default-jre git emacs vim

# This is java environment and tools for development
# docker build -t bonus02 .
# docker run --rm -ti bonus02
