FROM debian
MAINTAINER tmlkshk
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y build-essential git vim 

# This is a minimal kit for C development
# docker build -t bonus00 .
# docker run --rm -it bonus00
